variables:
  GIT_DEPTH: 0

stages:
  - push

push_to_github:
  stage: push
  image: alpine:latest
  before_script:
    - apk add --no-cache git
    - git config --global user.name "matti122"
    - git config --global user.email "matti122@whirlingbits.de"
  script:
    - git log --oneline --decorate --graph -20
    - git remote add github https://matti122:${GITHUB_TOKEN}@github.com/WhirlingBits/wb-idf-core.git
    - git push github --all
    - git push github --tags
  only:
    - main  # Only for `main`-Branch
  when: manual  # Job only starts manually